language: ruby
cache:
  - bundler
  - node_modules
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - sourceline: 'deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.4 multiverse'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x9ECBEC467F0CEB10'
    packages:
      - mongodb-org-server=3.4.5
services:
  - mongodb
  - rabbitmq
branches:
  only:
  - master
notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change
  slack:
    secure: NfcNb3LCyd7/ACYc6mDoBJZlBFIV5wKMMWs0On2DNeaDoD/EKCbQRQQVOHEvfsaqOM+5zmi9giYaV7cV+Gl+zfehZ/Q69x89YjWWVFeAp5QGDzoCnM7oaaTXygla52sfcL9Oi3rLgTWyjqMSS7tM2DW5d/V+iEjyilmavsUvRbU=
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 10.0
  - nvm use stable
  - npm install -g eslint
  - git clone -b master https://github.com/projectcypress/js-ecqm-engine.git /tmp/js-ecqm-engine
before_script:
  - git config --global user.email "travis@travis.ci"
  - git config --global user.name "Travis CI"
  - npm install eslint
  - yarn install --cwd /tmp/js-ecqm-engine
  - NODE_ENV=test /tmp/js-ecqm-engine/bin/rabbit_worker.js &
  - cp ./.travis/mongoid.yml ./config/mongoid.yml
env:
  - TEST_SUITE=cucumber
  - TEST_SUITE=audit
  - TEST_SUITE=models
  - TEST_SUITE=controllers
  - TEST_SUITE=helpers
  - TEST_SUITE=jobs
  - TEST_SUITE=units
script:
  - 'if [ ${TEST_SUITE} = "cucumber" ]; then
      bundle exec cucumber;
    elif [ ${TEST_SUITE} = "audit" ]; then
      bundle exec brakeman -qAzw1 &&
      bundle exec bundle-audit check --update --ignore CVE-2018-1000544 &&
      bundle exec overcommit --sign &&
      bundle exec overcommit --run;
    else
      RUBYOPT="-W0" bundle exec rake test:$TEST_SUITE;
    fi'
