development:
  sessions:
    default:
      database: cypress_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      options:
        consistency: :strong
      database: cypress_test
      hosts:
        - <%= ENV['TEST_DB_HOST'] || 'localhost' %>:27017

production:
  sessions:
    default:
      database: cypress_production
      hosts:
        - localhost:27017