# Mongoid Configuration for Travis CI
# ===================================
#
development:
  clients:
    default:
      database: cypress_development
      hosts:
        - localhost:27017
measure_eval:
  clients:
    default:
      database: cypress_eval
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: cypress_test<%= ENV['TEST_ENV_NUMBER'] %>
      hosts:
        - <%= ENV['TEST_DB_HOST'] || 'localhost' %>:27017
production:
  clients:
    default:
      database: cypress_production
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
